error-user             : User not found.
error-credentials      : Invalid credentials.
error-permissions      : You don't have permissions for this operation.
error-blocked          : Your account has been blocked.
error-project          : Project not found.
erorr-file             : File not found.
error-invalid          : Invalid data.
error-project-scripts  : Scripts are disabled for this project.
error-timeout          : A timeout.